# Generated by Django 5.1.4 on 2025-01-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Абонемент', 'verbose_name_plural': 'Абонементы'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_info',
            field=models.CharField(blank=True, max_length=50, verbose_name='Доп информация про скидку'),
        ),
    ]
