# Generated by Django 5.1.4 on 2025-01-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertificates', '0002_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='photo_short',
            field=models.ImageField(blank=True, null=True, upload_to='media/subscriptions/', verbose_name='Фото для карточки (для узких экранов)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/subscriptions/', verbose_name='Фото для карточки (нормальной по ширине)'),
        ),
    ]
