# Generated by Django 5.1.4 on 2025-01-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertificates', '0004_sertificateforsum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificateforsum',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='subscriptions/', verbose_name='Фото (нормальная по ширине)'),
        ),
        migrations.AlterField(
            model_name='sertificateforsum',
            name='photo_short',
            field=models.ImageField(blank=True, null=True, upload_to='subscriptions/', verbose_name='Фото (для узких экранов)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='subscriptions/', verbose_name='Фото для карточки (нормальной по ширине)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='photo_short',
            field=models.ImageField(blank=True, null=True, upload_to='subscriptions/', verbose_name='Фото для карточки (для узких экранов)'),
        ),
    ]
