# Generated by Django 5.1.4 on 2025-01-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertificates', '0008_alter_subscriptionspageinfo_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SertificateForSumPageinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(verbose_name='Прикольна фраза')),
                ('description', models.TextField(verbose_name='Опис')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар (*...)')),
                ('photo', models.FileField(upload_to='backgrounds/', verbose_name='Картинка сертифікату')),
            ],
            options={
                'verbose_name': 'Блок: суртифікати на суму',
                'verbose_name_plural': 'Блок: суртифікати на суму',
            },
        ),
    ]
