# Generated by Django 5.1.4 on 2025-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertificates', '0009_sertificateforsumpageinfo'),
        ('servises', '0004_alter_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sertificateforsumpageinfo',
            old_name='comment',
            new_name='comment_for_sum_sertificate',
        ),
        migrations.RemoveField(
            model_name='sertificateforsumpageinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sertificateforsumpageinfo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='sertificateforsumpageinfo',
            name='phrase',
        ),
        migrations.AddField(
            model_name='sertificateforsumpageinfo',
            name='background',
            field=models.FileField(default=111111111, upload_to='backgrounds/', verbose_name='Картинка для фону'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sertificateforsumpageinfo',
            name='description_for_servise_sertificate',
            field=models.TextField(default=11111111, verbose_name='Опис для сертифікату на послугу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sertificateforsumpageinfo',
            name='description_for_sum_sertificate',
            field=models.TextField(default=1111111, verbose_name='Опис для сертифікату на суму'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sertificateforsumpageinfo',
            name='photo_for_servise_sertificate',
            field=models.FileField(default=11111, upload_to='cards/', verbose_name='Картинка для сертифікату на послугу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sertificateforsumpageinfo',
            name='photo_for_sum_sertificate',
            field=models.FileField(default=111, upload_to='cards/', verbose_name='Картинка для сертифікату на суму'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sertificateforsumpageinfo',
            name='phrase_for_servise_sertificate',
            field=models.TextField(default=1, verbose_name='Прикольна фраза для сертифіката на послугу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sertificateforsumpageinfo',
            name='phrase_for_sum_sertificate',
            field=models.TextField(default=1, verbose_name='Прикольна фраза для сертифіката на суму'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sertificateforsumpageinfo',
            name='popular_servises',
            field=models.ManyToManyField(to='servises.service', verbose_name='Популярні послуги (ОБРАТИ РІВНО 3)'),
        ),
    ]
