# Generated by Django 5.1.4 on 2025-01-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertificates', '0011_rename_sertificateforsumpageinfo_sertificatespageinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='details',
        ),
        migrations.AddField(
            model_name='subscription',
            name='counts',
            field=models.JSONField(default=1, verbose_name='Види абонементів по кількості (JSON масив)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='durations',
            field=models.JSONField(default=1, verbose_name='Види абонементів по тривалості (JSON масив)'),
            preserve_default=False,
        ),
    ]
