# Generated by Django 5.1.4 on 2025-01-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertificates', '0012_remove_subscription_details_subscription_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='phrase',
            field=models.CharField(default=1, max_length=255, verbose_name='Прикольна фраза'),
            preserve_default=False,
        ),
    ]
