# Generated by Django 5.1.4 on 2025-01-23 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertificates', '0013_subscription_phrase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sertificateforsum',
            options={'verbose_name': 'Картка: сертифікат на суму', 'verbose_name_plural': 'Картки: Сертифікати на суму'},
        ),
        migrations.AlterModelOptions(
            name='sertificatespageinfo',
            options={'verbose_name': 'Секція: сертифікати на суму', 'verbose_name_plural': 'Секція: сертифікати на суму'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Картка: абонемент', 'verbose_name_plural': 'Картки: абонементи'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionspageinfo',
            options={'verbose_name': 'Секція: абонементи', 'verbose_name_plural': 'Секції: абонементи'},
        ),
        migrations.AddField(
            model_name='sertificateforsum',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sertificateforsum',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='sertificatespageinfo',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sertificatespageinfo',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='subscriptionspageinfo',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionspageinfo',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AlterField(
            model_name='sertificateforsum',
            name='altedgio_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на відгуки Альтеджио'),
        ),
        migrations.AlterField(
            model_name='sertificateforsum',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='subscriptions/', verbose_name='Фото (нормальне по ширині)'),
        ),
        migrations.AlterField(
            model_name='sertificateforsum',
            name='photo_short',
            field=models.ImageField(blank=True, null=True, upload_to='subscriptions/', verbose_name='Фото (для вузьких екранів)'),
        ),
        migrations.AlterField(
            model_name='sertificateforsum',
            name='price',
            field=models.FloatField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount_info',
            field=models.CharField(blank=True, max_length=50, verbose_name='Додаткова інформація про знижку'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва абонемента'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='subscriptions/', verbose_name='Фото для картки (нормальної по ширині)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='photo_short',
            field=models.ImageField(blank=True, null=True, upload_to='subscriptions/', verbose_name='Фото для картки (для вузьких екранів)'),
        ),
    ]
