# Generated by Django 5.1.4 on 2025-01-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('photo', models.ImageField(upload_to='media/employees/', verbose_name='Фото')),
                ('specialization_short', models.CharField(max_length=255, verbose_name='Специализация (коротко)')),
                ('specialization_detailed', models.TextField(verbose_name='Специализация (подробно)')),
                ('short_description', models.TextField(verbose_name='Короткое описание')),
                ('work_experience', models.FloatField(verbose_name='Стаж работы (в годах)')),
                ('education', models.TextField(verbose_name='Образование')),
                ('scientific_activity', models.TextField(blank=True, null=True, verbose_name='Научная деятельность')),
                ('professional_pathways', models.TextField(blank=True, null=True, verbose_name='Пути профессионального развития')),
                ('hobbies_and_interests', models.TextField(blank=True, null=True, verbose_name='Хобби, любимые фильмы, книги')),
                ('doctor_advice', models.TextField(blank=True, null=True, verbose_name='Советы от врача')),
                ('altedgio_reviews_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на отзывы на Альтеджио')),
                ('altedgio_booking_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на запись в Альтеджио')),
                ('telegram_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает ли')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
                ('show_on_all_specialists', models.BooleanField(default=True, verbose_name='Показывать на странице со всеми массажистами')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('services', models.ManyToManyField(related_name='employees', to='servises.service', verbose_name='Услуги')),
            ],
        ),
    ]
