# Generated by Django 5.1.4 on 2025-01-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.AddField(
            model_name='employee',
            name='ava_photo',
            field=models.ImageField(blank=True, upload_to='media/employees/', verbose_name='Фото для аватарки'),
        ),
        migrations.AddField(
            model_name='employee',
            name='card_photo',
            field=models.ImageField(blank=True, upload_to='media/employees/', verbose_name='Фото для карточки'),
        ),
        migrations.AddField(
            model_name='employee',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to='media/employees/', verbose_name='Главное фото'),
        ),
    ]
