# Generated by Django 5.1.4 on 2025-01-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг - текст, что будет показываться в адрессной строке на странице массажиста'),
        ),
    ]
