# Generated by Django 5.1.4 on 2025-01-13 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('date', models.DateField(blank=True, verbose_name='Дата оставления отзыва')),
                ('stars_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество звезд должно быть не меньше 1.'), django.core.validators.MaxValueValidator(5, message='Количество звезд должно быть не больше 5.')], verbose_name='Количество звезд')),
                ('text', models.TextField(max_length=320, verbose_name='Отзыв')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
    ]
