# Generated by Django 5.1.4 on 2025-01-13 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='specialist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='employees.employee', verbose_name='Специалист'),
            preserve_default=False,
        ),
    ]
