# Generated by Django 5.1.4 on 2025-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_ava_photo_alter_employee_card_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='scientific_activity',
            field=models.JSONField(blank=True, null=True, verbose_name='Научная деятельность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг - текст, что будет показываться в адрессной строке на странице массажиста'),
        ),
    ]
