# Generated by Django 5.1.4 on 2025-01-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_scientific_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва блоку')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Блок: спеціалісти',
                'verbose_name_plural': 'Блок: спеціалісти',
            },
        ),
    ]
