# Generated by Django 5.1.4 on 2025-01-22 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employeespageinfo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='feedbacks_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість відгуків'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='priority',
            field=models.PositiveIntegerField(default=1, verbose_name='Приорітет картки (двозначним числом)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='stars_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество звезд должно быть не меньше 1.'), django.core.validators.MaxValueValidator(5, message='Количество звезд должно быть не больше 5.')], verbose_name='Кількість зірок'),
            preserve_default=False,
        ),
    ]
