# Generated by Django 5.1.4 on 2025-01-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_feedbacks_count_employee_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='priority',
            field=models.PositiveIntegerField(unique=True, verbose_name='Приорітет картки (двозначним числом)'),
        ),
    ]
