# Generated by Django 5.1.4 on 2025-01-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_employee_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='feedbacks_count',
            field=models.CharField(max_length=50, verbose_name='Кількість відгуків (наприклад: "38 відгуків")'),
        ),
    ]
