# Generated by Django 5.1.4 on 2025-01-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_employee_feedbacks_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='time_created',
            field=models.DateField(auto_now=True, verbose_name='Дата редаування відгука'),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_created',
            field=models.DateField(auto_now=True, verbose_name='Дата створення запису'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
