# Generated by Django 5.1.4 on 2025-01-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_remove_comment_date_comment_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='time_addited',
            field=models.DateField(auto_now=True, verbose_name='Дата редагування запису'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата створення запису'),
        ),
    ]
