# Generated by Django 5.1.4 on 2025-01-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employee_time_addited_alter_employee_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='time_addited',
            new_name='time_updated',
        ),
    ]
