# Generated by Django 5.1.4 on 2025-01-23 10:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_comment_time_updated_alter_comment_time_created_and_more'),
        ('servises', '0006_alter_service_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Картка: співробітник', 'verbose_name_plural': 'Картки: співробітники'},
        ),
        migrations.AlterModelOptions(
            name='employeespageinfo',
            options={'verbose_name': 'Секція: спеціалісти', 'verbose_name_plural': 'Секція: спеціалісти'},
        ),
        migrations.AddField(
            model_name='employeespageinfo',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeespageinfo',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='altedgio_booking_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на запис в Альтеджіо'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='altedgio_reviews_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на відгуки в Альтеджіо'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='card_photo',
            field=models.ImageField(blank=True, upload_to='employees/', verbose_name='Фото для картки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doctor_advice',
            field=models.TextField(blank=True, null=True, verbose_name='Поради від лікаря'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.TextField(verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hobbies_and_interests',
            field=models.TextField(blank=True, null=True, verbose_name='Хобі, улюблені фільми, книги'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на Instagram'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Чи працює'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to='employees/', verbose_name='Головне фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(max_length=100, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='priority',
            field=models.PositiveIntegerField(unique=True, verbose_name='Пріоритет картки (двозначним числом)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='professional_pathways',
            field=models.TextField(blank=True, null=True, verbose_name='Шляхи професійного розвитку'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='scientific_activity',
            field=models.JSONField(blank=True, null=True, verbose_name='Наукова діяльність (JSON)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(related_name='employees', to='servises.service', verbose_name='Послуги (можна обирати декілька)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='short_description',
            field=models.TextField(verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='show_on_all_specialists',
            field=models.BooleanField(default=True, verbose_name='Показувати на сторінці зі всіма масажистами'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Показувати на головній сторінці'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialization_detailed',
            field=models.TextField(verbose_name='Спеціалізація (детально)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialization_short',
            field=models.CharField(max_length=255, verbose_name='Спеціалізація (коротко)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='stars_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Кількість зірок має бути не менше 1.'), django.core.validators.MaxValueValidator(5, message='Кількість зірок має бути не більше 5.')], verbose_name='Кількість зірок'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на Telegram'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_experience',
            field=models.FloatField(verbose_name='Досвід роботи (у роках)'),
        ),
    ]
