# Generated by Django 5.1.4 on 2025-01-23 10:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Картка: відгук', 'verbose_name_plural': 'Картки: відгуки'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Показувати на головній сторінці'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='employees.employee', verbose_name='Спеціаліст'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Кількість зірок має бути не менше 1.'), django.core.validators.MaxValueValidator(5, message='Кількість зірок має бути не більше 5.')], verbose_name='Кількість зірок'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=320, verbose_name='Відгук'),
        ),
    ]
