# Generated by Django 5.1.4 on 2025-01-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название массажа')),
                ('image', models.ImageField(upload_to='media/services/', verbose_name='Фотка (специальная)')),
                ('short_description', models.TextField(verbose_name='Короткое описание')),
                ('options', models.JSONField(verbose_name='Опции (длительность, части тела и цена)')),
                ('show_on_main', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
            ],
        ),
    ]
