# Generated by Django 5.1.4 on 2025-01-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
    ]
