# Generated by Django 5.1.4 on 2025-01-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0002_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_on_all_servises',
            field=models.BooleanField(default=False, verbose_name='Показывать на странице со всеми массажами'),
        ),
    ]
