# Generated by Django 5.1.4 on 2025-01-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0003_service_show_on_all_servises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='Фотка (специальная)'),
        ),
    ]
