# Generated by Django 5.1.4 on 2025-01-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0004_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.PositiveIntegerField(default=1, verbose_name='Приорітет картки (двозначним числом)'),
            preserve_default=False,
        ),
    ]
