# Generated by Django 5.1.4 on 2025-01-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0005_service_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='priority',
            field=models.PositiveIntegerField(unique=True, verbose_name='Приорітет картки (двозначним числом)'),
        ),
    ]
