# Generated by Django 5.1.4 on 2025-01-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_welcomeblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenInfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('icon', models.ImageField(upload_to='blocks/', verbose_name='Іконка')),
            ],
            options={
                'verbose_name': 'Блок: general information',
                'verbose_name_plural': 'Блок: general information',
            },
        ),
        migrations.AlterModelOptions(
            name='welcomeblock',
            options={'verbose_name': 'Блок: welcome', 'verbose_name_plural': 'Блок: welcome'},
        ),
        migrations.AlterField(
            model_name='welcomeblock',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст'),
        ),
    ]
