# Generated by Django 5.1.4 on 2025-01-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_geninfoblock_alter_welcomeblock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geninfoblock',
            name='icon',
            field=models.FileField(upload_to='blocks/', verbose_name='Іконка'),
        ),
    ]
