# Generated by Django 5.1.4 on 2025-01-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_geninfoblock_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomeblock',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blocks/', verbose_name='Фото (ТІЛЬКИ ДЛЯ company_photo)'),
        ),
        migrations.AlterField(
            model_name='welcomeblock',
            name='text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='welcomeblock',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва поля на сайті'),
        ),
    ]
