# Generated by Django 5.1.4 on 2025-01-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_welcomeblock_photo_alter_welcomeblock_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва поля на сайті')),
                ('text', models.TextField(verbose_name='Опис компанії')),
            ],
            options={
                'verbose_name': 'Блок: about as',
                'verbose_name_plural': 'Блок: about as',
            },
        ),
    ]
