# Generated by Django 5.1.4 on 2025-01-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_aboutasblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutasblock',
            name='photo_full',
            field=models.ImageField(default=1, upload_to='blocks/', verbose_name='Фото для повного екрану'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutasblock',
            name='photo_short',
            field=models.ImageField(default=12345234543543543534, upload_to='blocks/', verbose_name='Фото для вузького екрану'),
            preserve_default=False,
        ),
    ]
