# Generated by Django 5.1.4 on 2025-01-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='photo',
        ),
        migrations.AddField(
            model_name='logo',
            name='icon_flavic',
            field=models.FileField(default=121241234123123, upload_to='blocks/', verbose_name='Логотип для відображення на вкладках'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='icon_main',
            field=models.FileField(default=111111111, upload_to='blocks/', verbose_name='Логотип для відображення на сайті'),
            preserve_default=False,
        ),
    ]
