# Generated by Django 5.1.4 on 2025-01-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_remove_logo_photo_logo_icon_flavic_logo_icon_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySocials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Назва мережі')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Посилання')),
                ('icon', models.FileField(blank=True, upload_to='socials/', verbose_name='Іконка')),
            ],
            options={
                'verbose_name': 'Соц мережі компанії',
                'verbose_name_plural': 'Соц мережі компанії',
            },
        ),
    ]
