# Generated by Django 5.1.4 on 2025-01-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_advantages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advantages',
            new_name='AdvantagesBlock',
        ),
        migrations.RenameModel(
            old_name='GeneralBenefits',
            new_name='GeneralBenefitsBlock',
        ),
    ]
