# Generated by Django 5.1.4 on 2025-01-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_rename_advantages_advantagesblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAsBottomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва поля на сайті')),
                ('text', models.TextField(verbose_name='Опис')),
                ('photo_full', models.ImageField(upload_to='blocks/', verbose_name='Фото для повного екрану')),
            ],
            options={
                'verbose_name': 'Блок: about as bottom',
                'verbose_name_plural': 'Блок: about as bottom',
            },
        ),
    ]
