# Generated by Django 5.1.4 on 2025-01-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_aboutasbottomblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutasbottomblock',
            name='photo_full',
        ),
    ]
