# Generated by Django 5.1.4 on 2025-01-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_remove_aboutasbottomblock_photo_full'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutAsBottomBlock',
        ),
    ]
