# Generated by Django 5.1.4 on 2025-01-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_delete_aboutasbottomblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Rights reserved')),
            ],
            options={
                'verbose_name': 'Блок: general benefits',
                'verbose_name_plural': 'Блок: general benefits',
            },
        ),
    ]
