# Generated by Django 5.1.4 on 2025-01-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_otherpagesmainphotos_alter_footerblock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherpagesmainphotos',
            options={'verbose_name': 'Блок: фото для сторінки', 'verbose_name_plural': 'Блок: фото для сторінок'},
        ),
    ]
