# Generated by Django 5.1.4 on 2025-01-23 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_alter_otherpagesmainphotos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutasblock',
            options={'verbose_name': 'Секція: про нас', 'verbose_name_plural': 'Секція: про нас'},
        ),
        migrations.AlterModelOptions(
            name='advantagesblock',
            options={'verbose_name': 'Секція: переваги', 'verbose_name_plural': 'Секція: переваги'},
        ),
        migrations.AlterModelOptions(
            name='companysocials',
            options={'verbose_name': 'Секція: соціальні мережі компанії', 'verbose_name_plural': 'Секція: соціальні мережі компанії'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Секція: часті запитання', 'verbose_name_plural': 'Секція: часті запитання'},
        ),
        migrations.AlterModelOptions(
            name='footerblock',
            options={'verbose_name': 'Секція: футер', 'verbose_name_plural': 'Секція: футер'},
        ),
        migrations.AlterModelOptions(
            name='generalbenefitsblock',
            options={'verbose_name': 'Секція: загальні переваги', 'verbose_name_plural': 'Секція: загальні переваги'},
        ),
        migrations.AlterModelOptions(
            name='geninfoblock',
            options={'verbose_name': 'Секція: загальна інформація', 'verbose_name_plural': 'Секція: загальна інформація'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Секція: логотипи', 'verbose_name_plural': 'Секція: логотипи'},
        ),
        migrations.AlterModelOptions(
            name='otherpagesmainphotos',
            options={'verbose_name': 'Секція: фото для сторінок', 'verbose_name_plural': 'Секція: фото для сторінок'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Секція: політика конфіденційності', 'verbose_name_plural': 'Секція: політика конфіденційності'},
        ),
        migrations.AlterModelOptions(
            name='visitrecord',
            options={'verbose_name': 'ІНФОРМАЦІЯ: Запис клієнта', 'verbose_name_plural': 'ІНФОРМАЦІЯ: Записи клієнтів'},
        ),
        migrations.AlterModelOptions(
            name='welcomeblock',
            options={'verbose_name': 'Секція: вітальна', 'verbose_name_plural': 'Секція: вітальна'},
        ),
        migrations.AddField(
            model_name='aboutasblock',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutasblock',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='advantagesblock',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advantagesblock',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='companysocials',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companysocials',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='faq',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='footerblock',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footerblock',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='generalbenefitsblock',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalbenefitsblock',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='geninfoblock',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geninfoblock',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='logo',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='otherpagesmainphotos',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherpagesmainphotos',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AddField(
            model_name='welcomeblock',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='welcomeblock',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.TextField(verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.TextField(verbose_name='Запитання'),
        ),
        migrations.AlterField(
            model_name='footerblock',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Усі права захищені'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='customer_comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Коментар клієнта'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Чи клієнт обслугований?'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='welcomeblock',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blocks/', verbose_name='Фото (ЛИШЕ ДЛЯ company_photo)'),
        ),
    ]
