# Generated by Django 5.1.4 on 2025-01-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва блоку')),
                ('photo', models.FileField(upload_to='maps/', verbose_name="Фото дорожньої карти здоров'я")),
            ],
            options={
                'verbose_name': "Блок: карта здоров'я",
                'verbose_name_plural': "Блок: карта здоров'я",
            },
        ),
    ]
