# Generated by Django 5.1.4 on 2025-01-23 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mappageinfo',
            options={'verbose_name': "Секція: карта здоров'я", 'verbose_name_plural': "Секція: карта здоров'я"},
        ),
        migrations.AddField(
            model_name='mappageinfo',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappageinfo',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
    ]
